version: "3.7"

services:
  micro-service:
    image: "spike19820318/test-01:latest"
    container_name: "test-01"
    ports:
      - "8080:8080"
    environment:
      - NEW_RELIC_APP_NAME=test-01
      - NEW_RELIC_LICENSE_KEY=${YOUR_NEW_RELIC_LICENSE_KEY}
      - ENV_NEW_RELIC_LOG_FILE_NAME=STDOUT
      - SPRING_PROFILES_ACTIVE=sit